### ISSUE TITLE
[Help] Trying pass Onboard wireless

### ISSUE THREAD

**Issue by Milor123** [FinchSec/wifite2-docker#1]
Hey bro, i am trying mount my wifi onboard card using your settings over the image leplusorg/kali, i am in manjaro in my real machine.

```
version: '3'
services:
  MrKali:
    image: leplusorg/kali
    container_name: kali-net
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_ADMIN
    privileged: true
    stdin_open: true  # equivalente a -i
    tty: true         # equivalente a -t
    pid: host
   
```

its stucks in  `enabling monitor mode`

![image](https://github.com/user-attachments/assets/a4dba920-bbc3-40b5-a01b-7b580adf4b57)
then if I try 

```
┌──(root㉿noe-systemproductname)-[/]
└─# sudo airmon-ng start wlo1

Found 2 processes that could cause trouble.
Kill them using 'airmon-ng check kill' before putting
the card in monitor mode, they will interfere by changing channels
and sometimes putting the interface back in managed mode

    PID Name
    952 NetworkManager
   1153 wpa_supplicant

PHY	Interface	Driver		Chipset

phy0	wlo1		iwlwifi		Intel Corporation Alder Lake-S PCH CNVi WiFi (rev 11)

Failed to set wlo1 down using ip

ERROR adding monitor mode interface: command failed: Operation not permitted (-1)
```

Then If i try in my real machine do manaully the and then use wifi in docker container.
![image](https://github.com/user-attachments/assets/87077f1c-0aeb-468e-bb60-d89f7e61e601)

Why happend this, should I do add something special for share my board card?
My host pc is connecting with Cable using Rj45, and the wifi is enabled on the board. The problem only happened in the docker container, in my hosts wifite works well
